// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.
// Edit design-tokens/tokens.json and run `npm run build:tokens`.

/** Compile-time color palette for Tailwind. Dark mode is canonical;
 *  light mode is swapped at runtime via the [data-theme="light"] CSS block. */
export const ngColors = {
  "bg": "#0B0E14",
  "surface": "#111621",
  "elevated": "#1A1F2E",
  "border": "#1E2433",
  "primary": "#38BDF8",
  "accent": "#A78BFA",
  "success": "#34D399",
  "warning": "#FBBF24",
  "critical": "#F87171",
  "text-primary": "#F1F5F9",
  "text-secondary": "#94A3B8",
  "text-muted": "#64748B"
} as const;

export const ngRadius = {
  "card": "16px",
  "button": "8px",
  "pill": "9999px"
} as const;

export const ngFont = {
  "sans": "var(--font-inter), system-ui, sans-serif",
  "mono": "var(--font-mono), monospace"
} as const;
