#!/usr/bin/env node
/**
 * Lightweight token build — reads design-tokens/tokens.json and emits:
 *   src/styles/tokens.gen.css   (CSS custom properties for both themes)
 *   src/styles/tokens.gen.ts    (a typed object Tailwind can spread into colors)
 *
 * No dependencies. ~80 lines. Style Dictionary is overkill for the
 * Nodeglow scale; if/when we grow beyond 50 tokens this is the file to
 * replace with a real tool.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const TOKENS_PATH = resolve(ROOT, 'design-tokens/tokens.json');
const CSS_OUT = resolve(ROOT, 'src/styles/tokens.gen.css');
const TS_OUT = resolve(ROOT, 'src/styles/tokens.gen.ts');

const tokens = JSON.parse(readFileSync(TOKENS_PATH, 'utf8'));

// ── CSS output ──────────────────────────────────────────────────────────────

function cssBlock(theme, palette) {
  const selector = theme === 'dark'
    ? ':root,\n[data-theme="dark"]'
    : '[data-theme="light"]';
  const lines = Object.entries(palette).map(
    ([name, value]) => `  --ng-${name}: ${value};`
  );
  return `${selector} {\n${lines.join('\n')}\n}`;
}

const cssBlocks = [
  '/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand. */',
  '/* Edit design-tokens/tokens.json and run `npm run build:tokens`.       */',
  '',
  cssBlock('dark', tokens.color.dark),
  '',
  cssBlock('light', tokens.color.light),
  '',
  ':root {',
  ...Object.entries(tokens.radius).map(
    ([k, v]) => `  --ng-radius-${k}: ${v};`
  ),
  '}',
];

mkdirSync(dirname(CSS_OUT), { recursive: true });
writeFileSync(CSS_OUT, cssBlocks.join('\n') + '\n');

// ── TypeScript output ───────────────────────────────────────────────────────
// Tailwind doesn't read CSS variables for compile-time class generation
// (e.g. `bg-ng-primary`), so we also emit a static palette object that
// gets spread into tailwind.config.ts. The DARK palette is the canonical
// one for compile-time — light mode is handled at runtime via [data-theme].

const tsContent = [
  '// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.',
  '// Edit design-tokens/tokens.json and run `npm run build:tokens`.',
  '',
  '/** Compile-time color palette for Tailwind. Dark mode is canonical;',
  ' *  light mode is swapped at runtime via the [data-theme="light"] CSS block. */',
  'export const ngColors = ' + JSON.stringify(tokens.color.dark, null, 2) + ' as const;',
  '',
  'export const ngRadius = ' + JSON.stringify(tokens.radius, null, 2) + ' as const;',
  '',
  'export const ngFont = ' + JSON.stringify(tokens.font, null, 2) + ' as const;',
  '',
];
writeFileSync(TS_OUT, tsContent.join('\n'));

console.log(`✓ tokens built — ${CSS_OUT}`);
console.log(`✓ tokens built — ${TS_OUT}`);
