#!/usr/bin/env node
/**
 * Token build. Reads design-tokens/tokens.json and emits
 *   src/styles/tokens.gen.css  CSS custom properties (--ng-*) for both themes
 *   src/styles/tokens.gen.ts   typed token names + raw values for JS consumers
 *
 * Value syntax: `{name}` is a reference to another token and becomes
 * `var(--ng-name)`, so derived tokens (accent-soft, glow) follow the
 * active theme automatically.
 *
 * Selectors:
 *   :root, [data-theme="dark"]   dark theme (default)
 *   [data-theme="light"]         light theme (set on <html> before first paint,
 *                                see src/lib/theme-script.ts)
 *   :root, [data-theme]          shared tokens; repeated on every themed
 *                                element so derived values recompute in subtrees
 *
 * No dependencies on purpose.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const TOKENS_PATH = resolve(ROOT, 'design-tokens/tokens.json');
const CSS_OUT = resolve(ROOT, 'src/styles/tokens.gen.css');
const TS_OUT = resolve(ROOT, 'src/styles/tokens.gen.ts');

const tokens = JSON.parse(readFileSync(TOKENS_PATH, 'utf8'));
// Keys starting with "_" are comments.
const strip = (o) => Object.fromEntries(Object.entries(o).filter(([k]) => !k.startsWith('_')));
const dark = strip(tokens.theme.dark);
const light = strip(tokens.theme.light);
const shared = strip(tokens.shared);

// ── validation ─────────────────────────────────────────────────────────────
const known = new Set([...Object.keys(dark), ...Object.keys(shared)]);
const errors = [];
for (const k of Object.keys(dark)) if (!(k in light)) errors.push(`light theme is missing "${k}"`);
for (const k of Object.keys(light)) if (!(k in dark)) errors.push(`dark theme is missing "${k}"`);
for (const [group, obj] of Object.entries({ dark, light, shared })) {
  for (const [k, v] of Object.entries(obj)) {
    for (const m of String(v).matchAll(/\{([a-z0-9-]+)\}/g)) {
      if (!known.has(m[1])) errors.push(`${group}.${k} references unknown token {${m[1]}}`);
    }
  }
}
if (errors.length) {
  console.error('✗ design tokens are invalid:\n  ' + errors.join('\n  '));
  process.exit(1);
}

// ── CSS output ─────────────────────────────────────────────────────────────
const toCss = (v) => String(v).replace(/\{([a-z0-9-]+)\}/g, 'var(--ng-$1)');

function block(selector, obj) {
  const lines = Object.entries(obj).map(([k, v]) =>
    k === 'color-scheme' ? `  color-scheme: ${v};` : `  --ng-${k}: ${toCss(v)};`,
  );
  return `${selector} {\n${lines.join('\n')}\n}`;
}

const css = [
  '/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.        */',
  '/* Edit design-tokens/tokens.json and run `npm run build:tokens`.            */',
  '/* Reference: docs/design/04-design-system.md                                */',
  '',
  block(':root,\n[data-theme="dark"]', dark),
  '',
  block('[data-theme="light"]', light),
  '',
  block(':root,\n[data-theme]', shared),
  '',
].join('\n');

mkdirSync(dirname(CSS_OUT), { recursive: true });
writeFileSync(CSS_OUT, css);

// ── TypeScript output ──────────────────────────────────────────────────────
const themeNames = Object.keys(dark).filter((k) => k !== 'color-scheme');
const sharedNames = Object.keys(shared);
const json = (o) => JSON.stringify(o, null, 2);

const ts = [
  '// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.',
  '// Edit design-tokens/tokens.json and run `npm run build:tokens`.',
  '',
  '/** Names of the per-theme tokens (each is a CSS variable `--ng-<name>`). */',
  `export const ngThemeTokenNames = ${json(themeNames)} as const;`,
  '',
  '/** Names of the theme-independent and derived tokens. */',
  `export const ngSharedTokenNames = ${json(sharedNames)} as const;`,
  '',
  'export type NgThemeToken = (typeof ngThemeTokenNames)[number];',
  'export type NgSharedToken = (typeof ngSharedTokenNames)[number];',
  'export type NgToken = NgThemeToken | NgSharedToken;',
  'export type NgThemeName = \'dark\' | \'light\';',
  '',
  '/** `var(--ng-<name>)` for inline styles. Prefer Tailwind classes where possible. */',
  'export function ngVar(name: NgToken): string {',
  '  return `var(--ng-${name})`;',
  '}',
  '',
  '/** Raw token values as written in tokens.json (`{ref}` = reference to another token).',
  ' *  For JS consumers that cannot read CSS variables at build time. At runtime, prefer',
  ' *  readToken() from lib/chart-theme so the value follows the active theme. */',
  `export const ngTokensRaw = ${json({ dark, light, shared })} as const;`,
  '',
  `export const ngRadius = ${json({
    card: shared.radius,
    sm: shared['radius-sm'],
    control: shared['radius-ctl'],
    chip: shared['radius-chip'],
    lg: shared['radius-lg'],
    pill: shared['radius-pill'],
  })} as const;`,
  '',
  `export const ngFont = ${json({
    sans: shared['font-ui'],
    display: shared['font-display'],
    mono: shared['font-mono'],
  })} as const;`,
  '',
].join('\n');
writeFileSync(TS_OUT, ts);

console.log(`✓ tokens built — ${themeNames.length} theme tokens × 2, ${sharedNames.length} shared`);
